# Generated by Django 5.2.4 on 2025-08-18 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0003_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routeplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
        migrations.AddField(
            model_name='routeplace',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route'),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='routes.route'),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='routeplace',
            unique_together={('route', 'place'), ('route', 'stop_order')},
        ),
        migrations.AlterUniqueTogether(
            name='savedroute',
            unique_together={('user', 'route')},
        ),
    ]
