# Generated by Django 5.2.4 on 2025-08-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_embedding'),
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routeplace',
            unique_together={('route', 'place'), ('route', 'stop_order')},
        ),
    ]
