# Generated by Django 5.2.4 on 2025-08-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_routeplace_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
