# Generated by Django 5.2.4 on 2025-08-18 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='tags.tag'),
        ),
        migrations.AddField(
            model_name='placelike',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placelikes', to='places.place'),
        ),
    ]
