# Generated by Django 5.2.4 on 2025-08-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_is_unique_place_summary'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', to='tags.tag'),
        ),
    ]
