# Generated by Django 5.2.4 on 2025-08-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_class',
            field=models.IntegerField(default=0),
        ),
    ]
