# Generated by Django 5.2.4 on 2025-08-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_place_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
