# Generated by Django 5.2.4 on 2025-08-08 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_placelike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placelike',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placelikes', to='places.place'),
        ),
    ]
