# Generated by Django 5.2.4 on 2025-08-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placelike_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_class',
            field=models.IntegerField(choices=[(1, '레포츠'), (2, '쇼핑'), (3, '관광지'), (4, '문화시설')], default=0),
        ),
    ]
