# Generated by Django 5.2.4 on 2025-08-12 07:37

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_placelike_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
