# Generated by Django 5.2.4 on 2025-08-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_place_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='embedding',
        ),
    ]
