# Generated by Django 5.2.4 on 2025-08-13 08:17

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_place_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
