# Generated by Django 5.2.4 on 2025-08-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_place_class'),
        ('places', '0010_place_embedding'),
    ]

    operations = [
    ]
