# Generated by Django 5.2.4 on 2025-08-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_merge_20250818_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_class',
            field=models.IntegerField(default=0),
        ),
    ]
