# Generated by Django 5.2.4 on 2025-08-14 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_embedding'),
        ('reviews', '0001_initial'),
        ('routes', '0004_route_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='places.place', verbose_name='장소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='routes.route', verbose_name='여행 경로'),
        ),
    ]
