# Generated by Django 5.2.4 on 2025-08-14 08:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_place_alter_review_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='route',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='0.0 ~ 5.0 (0.5 단위)', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('5.0'))]),
        ),
    ]
