# Generated by Django 5.2.4 on 2025-08-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_initial'),
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='routes.route'),
        ),
    ]
