# Generated by Django 5.2.4 on 2025-08-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_route_remove_review_title_and_more'),
        ('routes', '0004_route_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='routes.route', verbose_name='여행 경로'),
        ),
    ]
