# Generated by Django 5.2.4 on 2025-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='TEST', max_length=200, verbose_name='게시물 제목'),
            preserve_default=False,
        ),
    ]
