# Generated by Django 5.2.4 on 2025-08-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='summary',
        ),
    ]
