# Generated by Django 5.2.4 on 2025-08-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_review_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/', verbose_name='사진'),
        ),
    ]
