# Generated by Django 5.2.4 on 2025-08-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_options_alter_review_rating'),
        ('routes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='route',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='routes.route', verbose_name='여행 경로'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='사진 URL'),
        ),
    ]
