# Generated by Django 5.2.4 on 2025-08-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_options_alter_review_rating'),
        ('reviews', '0006_remove_reviewphoto_url_reviewphoto_image'),
    ]

    operations = [
    ]
